const data = [
    {
        _id: 1,
        name: "Zinger Burger1",
        category: "burger",
        image: "https://tse1.mm.bing.net/th?id=OIP.Ah8LHrAHkdfD19U-r366bAHaHV&pid=Api&P=0",
        price: 400,
        rating: 4,
    },
    {
        _id: 2,
        name: "Meal Burger",
        category: "burger",
        image: "https://tse3.explicit.bing.net/th?id=OIF.p2Oy3eyGp1NNJDog0i%2b4tg&pid=Api&P=0&h=180",
        price: 500,
        rating: 4,
    },
    {
        _id: 3,
        name: "Special Burger",
        category: "burger",
        image: "https://tse2.mm.bing.net/th?id=OIP.DJcNvH2CYuDYyZlep1STKAHaEz&pid=Api&P=0&h=180",
        price: 550,
        rating: 4,
    },
    {
        _id: 4,
        name: "Hamburger Meat Burger4",
        category: "burger",
        image: "https://tse4.mm.bing.net/th?id=OIP.H07SGPpx-swRy0WfmnDIdwHaHa&pid=Api&P=0&h=180",
        price: 600,
        rating: 4,
    },
    {
        _id: 5,
        name: "Kabab stuffer pizza",
        category: "pizza",
        image: "https://tse1.mm.bing.net/th?id=OIP.1_F_D-W79M_QcT_f34DN-wHaFN&pid=Api&P=0&h=180",
        price: 1800,
        rating: 4,
    },
    {
        _id: 6,
        name: "Checken cheese stuffer",
        category: "pizza",
        image: "https://tse1.explicit.bing.net/th?id=OIP.oP1MEsBvts8Vg01e7Kw9JAHaEj&pid=Api&P=0&h=180",
        price: 1750,
        rating: 4,
    },
    {
        _id: 7,
        name: "Checken cheese stuffer",
        category: "pizza",
        image: "https://tse4.mm.bing.net/th?id=OIP.cqdhtrwdUBe-7cckIrlV4AHaE7&pid=Api&P=0&h=180",
        price: 1750,
        rating: 4,
    },
    {
        _id: 8,
        name: "Salad pizza",
        category: "pizza",
        image: "https://tse4.mm.bing.net/th?id=OIP.n0nfgtxzRBAWWChSSuPECAHaE8&pid=Api&P=0&h=180",
        price: 1250,
        rating: 4,
    },


    {
        _id: 9,
        name: "Role Sandwich",
        category: "sandwich",
        image: "https://tse2.explicit.bing.net/th?id=OIP.v9dbWr_3vNlZ_arN3gFi3AHaE8&pid=Api&P=0&h=180",
        price: 800,
        rating: 4,
    },
    {
        _id: 10,
        name: "Salad Sandwich",
        category: "sandwich",
        image: "https://tse1.mm.bing.net/th?id=OIP.ueTmPDkn-fXtYdltOL2ZcgHaE7&pid=Api&P=0&h=180",
        price: 500,
        rating: 4,
    },
    {
        _id: 11,
        name: "Zingure Sandwich",
        category: "sandwich",
        image: "https://tse1.mm.bing.net/th?id=OIP.eBd2FmoazT1dvCrGpem0RwHaDO&pid=Api&P=0&h=180",
        price: 1250,
        rating: 4,
    },
    {
        _id: 12,
        name: "Beef Sandwich",
        category: "sandwich",
        image: "https://tse2.mm.bing.net/th?id=OIP.yc_6onL9ZuQMuhMHZEiAlgHaEo&pid=Api&P=0&h=180",
        price: 1550,
        rating: 4,
    },




    {
        _id: 13,
        name: "Grapps Smoothy ",
        category: "Smoothy ",
        image: "https://tse1.mm.bing.net/th?id=OIP.jvH2-7McgSzazUOfP-bqJwHaHa&pid=Api&P=0&h=180",
        price: 800,
        rating: 4,
    },
    {
        _id: 14,
        name: "Strubry Smoothy ",
        category: "Smoothy ",
        image: "https://tse1.mm.bing.net/th?id=OIP.ZPS2kwJ4npmOfHHKeRMvaAHaHa&pid=Api&P=0&h=180",
        price: 500,
        rating: 4,
    },
    {
        _id: 15,
        name: "Orange Smoothy ",
        category: "Smoothy ",
        image: "https://tse2.mm.bing.net/th?id=OIP.LJYdmKbv8Yudgj93cEXWbAHaLH&pid=Api&P=0&h=180",
        price: 1250,
        rating: 4,
    },
    {
        _id: 16,
        name: "All in one Smoothy ",
        category: "Smoothy ",
        image: "https://tse2.mm.bing.net/th?id=OIP.yqDA4z8JXXIWFyVa_dpp6gHaE8&pid=Api&P=0&h=180",
        rating: 4,
        price: 1800,
    },


    
    {
        _id: 17,
        name: "Grapps Snaks  ",
        category: "Snaks",
        image: "https://tse2.mm.bing.net/th?id=OIP.4J6dGeUx_ju6lX79bpUl5AHaDt&pid=Api&P=0&h=180",
        price: 800,
        rating: 4,
    },
    {
        _id: 18,
        name: "Strubry Snaks  ",
        category: "Snaks  ",
        image: "https://tse2.mm.bing.net/th?id=OIP.PKm7dV_mhfPMS2aQfzL9RQHaKt&pid=Api&P=0&h=180",
        price: 500,
        rating: 4,
    },
    {
        _id: 19,
        name: "Banana Snaks  ",
        category: "Snaks  ",
        image: "https://tse4.mm.bing.net/th?id=OIP.Bk04fQoJ60tC2ViRXUKtOQHaE8&pid=Api&P=0&h=180",
        price: 1250,
        rating: 4,
    },
    {
        _id: 20,
        name: "All in one Snaks ",
        category: "Snaks",
        image: "https://tse4.mm.bing.net/th?id=OIP.GvwuN-8LmIXLfWIh7TqBqQHaD4&pid=Api&P=0&h=180",
        price: 100,
        rating: 4,
    },


    {
        _id: 21,
        name: "Sugar Free Drink",
        category: " Drink",
        image: "https://tse3.mm.bing.net/th?id=OIP.WsbBqAzhNU7NNC2vWJpx7gHaEv&pid=Api&P=0&h=180",
        price: 800,
        rating: 4,
    },
    {
        _id: 22,
        name: "Soda Drink",
        category: " Drink",
        image: "https://tse4.mm.bing.net/th?id=OIP.rEza_SwuqwiIc_d1lFGEdAHaEK&pid=Api&P=0&h=180",
        price: 500,
        rating: 4,
    },
    {
        _id: 23,
        name: "Alcoholic Drink",
        category: " Drink",
        image: "https://tse2.mm.bing.net/th?id=OIP.VbP9vd3gJy8UDx9PB5kUxQHaE_&pid=Api&P=0&h=180",
        price: 1250,
        rating: 4,
    },
    {
        _id: 24,
        name: "Shakes Drink",
        category: " Drink",
        image: "https://tse1.mm.bing.net/th?id=OIP.XrfvR7fPVaMtLnfKUWHnfgHaEK&pid=Api&P=0&h=180",
        price: 100,
        rating: 4,
    },

]

export default data;